title: Red Data Tools
markdown: kramdown
highlighter: rouge
copyright_year: 2017-2018
exclude:
  - "README.md"
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
description:
  en: "Data processing with Ruby!"
  ja: "Rubyでデータ処理！"

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: ja
      type: posts
    values:
      path_prefix: /ja/blog/
      upper_level: /ja/blog/
      layout: post
      language: ja
      country: JP
  - scope:
      path: ja
    values:
      path_prefix: /ja/
      layout: base
      language: ja
      country: JP
  - scope:
      path: ""
      type: posts
    values:
      path_prefix: /blog/
      upper_level: /blog/
      layout: post
      language: en
      country: US
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: base
      language: en
      country: US
